@extends('layouts.app')

@section('content')
<section id="terms" class="terms">
    <div class="terms-container mt-5">
        <div class="terms pb-5">
            <h3 class="mb-3 font-24-faq">Termly’s Terms Of Use</h3>
            <div class="row">
                <div class="col-12">
                    <div class="terms-accordion d-flex align-items-center justify-content-between">
                        <div class="terms-text-font">AGREEMENT TO TERMS</div>
                        <div class="terms-text-font">                            
                            We are Termly Inc., doing business as Termly (“Termly,” “we,” “us,” or “our”), a company registered in the State of Delaware. We operate the website https://termly.io (the “Website”) through which we provide you our services, (collectively, the “Services” which include the provision and use of the Website).

                            You can contact us by phone at (855) 234-5020, by email at info@termly.io, or by post to Termly Inc., 8 The Grn Ste B, Dover, DE 19901.

                            These Terms of Use constitute a legally binding agreement made between you, whether personally or on behalf of an entity (“you”) and concerning your access to and use of the Website and the Services. You agree that by accessing the Services, you have read, understood, and agree to be bound by all of these Terms of Use. IF YOU DO NOT AGREE WITH ALL OF THESE TERMS OF USE, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SERVICES AND YOU MUST DISCONTINUE USE IMMEDIATELY.

                            Supplemental terms and conditions or documents that may be posted on the Website from time to time are hereby expressly incorporated herein by reference. We reserve the right, in Termly’s sole discretion, to make changes or modifications to these Terms of Use from time to time. We will alert you about any changes by updating the “Last updated” date of these Terms of Use, and you waive any right to receive specific notice of each such change. It is your responsibility to periodically review these Terms of Use to stay informed as each time you access the Services, you will be subject to, and will be deemed to have been made aware of and to have accepted, the then applicable Terms of Use.

                            The Services are intended for business users who are at least 18 years old. Persons under the age of 18 are not permitted to use or register for the Services.

                            TABLE OF CONTENTS
                            OUR WEBSITE AND SERVICES
                            INTELLECTUAL PROPERTY RIGHTS
                            USER REPRESENTATIONS
                            USER REGISTRATION
                            FEES AND PAYMENT
                            PROHIBITED ACTIVITIES
                            THIRD-PARTY WEBSITES AND CONTENT
                            SERVICES MANAGEMENT
                            PRIVACY NOTICE
                            DIGITAL MILLENNIUM COPYRIGHT ACT (DMCA) NOTICE AND POLICY
                            TERM AND TERMINATION
                            MODIFICATIONS AND INTERRUPTIONS
                            GOVERNING LAW
                            DISPUTE RESOLUTION
                            CORRECTIONS
                            DISCLAIMER
                            LIMITATIONS OF LIABILITY
                            INDEMNIFICATION
                            USER DATA
                            ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES
                            CALIFORNIA USERS AND RESIDENTS
                            OTHER IMPORTANT INFORMATION
                            CONTACT US
                            1. OUR WEBSITE AND SERVICES
                            We are not lawyers nor a law firm, but we help you with compliance in relation to your privacy and contractual obligations. We provide you a software (the “Software”), that you access remotely via the cloud, that you can use for (a) consent management (“Consent Platform”); and (b) the generation of policies, legal agreements, disclaimers, and other documents generated by the Services using information related to your business or organization that you enter into the Software (collectively “Forms”).

                            The information, Consent Platform, and Forms provided when using the Services are not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. Accordingly, those persons who choose to access the Services from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.

                            The Services are not tailored to comply with industry-specific regulations (including Health Insurance Portability and Accountability Act (HIPAA), Federal Information Security Management Act (FISMA), etc.), so if your interactions would be subjected to such laws, you may not use these Services. You may not use the Services in a way that would violate the Gramm-Leach-Bliley Act (GLBA).

                            Using Termly’s Forms
                            You may use any Forms generated by the Software through your use of our generator(s) for your business or organization. It is your responsibility to determine whether the Forms generated by the Software are appropriate for your use. From time to time, we may notify you that a particular Form may need to be updated in response to changes in applicable laws or other guidance, rules or regulations, and you are responsible for determining whether to update the Forms used in your business or organization.

                            WE DO NOT REPRESENT THAT THE FORMS WILL MEET YOUR SPECIFIC GOALS, PROTECT YOUR SPECIFIC INTERESTS, OR WITHSTAND CHALLENGES TO THEIR LEGAL OR FACTUAL SUFFICIENCY. THE FORMS ARE NOT PROVIDED WITH ANY GUARANTY, WARRANTY, OR REPRESENTATION AS TO QUALITY OR SUITABILITY FOR ANY PARTICULAR PURPOSE. The Forms are general in nature and may not be sufficient to protect you against a specific risk, problem or dispute. Our software’s generation of a Form does not constitute the practice of law and is not legal counsel or advice. You should not rely on a Form as a substitute for consultation with an attorney.

                            Using Termly’s Consent Platform
                            If you use Termly’s Consent Platform, you may access the features of the Software designed to track and monitor consents given or withdrawn by the users of your website(s) with regard to cookies or similar tracking technology used on such website(s).

                            TERMLY IS NOT LIABLE FOR YOUR FAILURE TO DISABLE OR REMOVE COOKIES IF YOUR USERS DO NOT CONSENT TO THEIR USE.

                            2. INTELLECTUAL PROPERTY RIGHTS
                            Unless otherwise indicated, we retain all right, title, and interest in and to the Software and the Website, including without limitation all graphics, user interfaces, databases, functionality, software, website designs, audio, video, text, photographs, graphics, logos, and trademarks or service marks reproduced through the System. These Terms of Use do not grant you any intellectual property license or rights in or to the Software and the Website or any of its components, except to the limited extent that these Terms of Use specifically sets forth your license rights to it. You recognize that the Software and the Website and their components are protected by copyright and other laws.

                            Conditioned upon your compliance with these Terms of Use and, if applicable, your payment of the Subscription Fees, we grant you the rights to reproduce, modify, and publicly display the Forms and use the Consent Platform (all together “Content”) on your website or mobile application. In addition, as to a Form intended to serve as a legal agreement between you and a counterparty, we grant you the right to distribute that Form to the counterparty to the extent reasonably necessary for your counterparty to execute the agreement. Under no circumstances may you use the Forms and use the Consent Platform for commercial purposes other than to facilitate compliance with applicable laws and best practices or the execution of agreements by your own business or organization. The Forms and the Consent Platform generated by the Software are licensed, not sold, and you receive no title to or ownership of the Forms or the Consent Platform.

                            You and Termly agree that none of the Feedback (as defined below) you or your users provide to us constitute confidential information, and nothing in these Terms of Use or in our dealings arising out of or related to subject matter of these Terms of Use will restrict our right to use, profit from, disclose, publish, keep secret, or otherwise exploit Feedback, without compensating or crediting you or the user in question. You hereby grant us a perpetual, irrevocable right and license to exploit the Feedback in any and every way and subject to applicable law waive any moral rights in such Feedback. Feedback will not constitute your confidential information. (“Feedback” refers to any suggestion or idea for improving or otherwise modifying any of Termly’s products or services.)

                            3. USER REPRESENTATIONS
                            By using the Services, you represent and warrant that: (1) all registration information you submit will be true, accurate, current, and complete; (2) you will maintain the accuracy of such information and promptly update such registration information as necessary; (3) you have the legal capacity and you agree to comply with these Terms of Use; (4) you are not a minor in the jurisdiction in which you reside; (5) you will not access the Services through automated or non-human means, whether through a bot, script or otherwise; (6) you will not use the Services for any illegal or unauthorized purpose; and (7) your use of the Services will not violate any applicable law or regulation.

                            If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the Services (or any portion thereof).

                            4. USER REGISTRATION
                            You may be required to register with the Services. You agree to keep your password confidential and will be responsible for all use of your account and password. We reserve the right to remove, reclaim, or change a username you select if we determine, in our sole discretion, that such username is inappropriate, obscene, or otherwise objectionable.

                            5. FEES AND PAYMENT
                            Termly offers free and paid account options. You can create a free account (“Free Account”) without providing any credit card information, but your access to our Website’s features will be limited. Depending on your needs, you may want to access more or all of Termly’s Services by creating or upgrading to a paid account (“Paid Account”). You can create or upgrade to a Paid Account by signing up for one of Termly’s subscription plans (“Subscription Plans” and each a “Subscription”).

                            You can find information about our pricing options and available Subscription Plans on the following page here.

                            Fees for Subscriptions
                            Fees for Subscriptions (“Subscription Fees”) shall be based on the length of your Subscription (“Subscription Period”). All Subscriptions will auto-renew at the end of the then Subscription Period.

                            We bill you for all initial and recurring Subscription Fees through an online billing account and you agree to provide (and keep updated) current, complete, and accurate purchase and account information including email address, payment method, and payment card expiration date, so that we can process your payments and contact you as needed.

                            Our prices may be updated from time to time so please make sure that you check our current Subscription Fees before placing your order. All payments shall be in USD, EUR, or GBP.

                            Accepted Forms of Payment
                            We accept the following forms of payment:

                            Visa
                            Mastercard
                            American Express
                            Discover
                            Any other Stripe supported card brands
                            You agree to pay all charges or fees at the prices then in effect for your Subscription, and you authorize us to charge your chosen payment provider for any such amounts upon placing your order. If your Subscription is subject to recurring charges, then you consent to our charging your payment method on a recurring basis without requiring your prior approval for each recurring charge, until you notify us of your cancellation in accordance with the cancellation information described in this section below.

                            We reserve the right to correct any errors or mistakes in pricing, even if we have already requested or received payment. We also reserve the right to refuse any order placed through the Services. In such case we will notify you by email and refund you any Subscription Fees that you have paid.

                            Sales Tax
                            Sales tax will be added to the price of purchases as deemed required by us. Amounts due under these Terms of Use are payable to us without deduction and are net of any tax, tariff, duty, or assessment imposed by any government authority (national, state, provincial, or local), including without limitation any sales, use, excise, ad valorem, property, withholding, or value-added tax, whether or not withheld at the source (collectively, “Sales Tax”). Except as forbidden by applicable law, we may require that you submit applicable Sales Taxes to us. However, the preceding sentence does not apply to the extent that you are tax exempt, provided you give us a valid tax exemption certificate within thirty (30) days of the start of your Subscription. Our failure to include any applicable tax in an invoice will not waive or dismiss the parties’ rights or obligations pursuant to this Section. If applicable law requires withholding or deduction of Sales Taxes or any other tax or duty, you shall separately pay us the withheld or deducted amount, over and above fees due. For the avoidance of doubt, this Section does not govern taxes based on our net income.

                            Account Upgrades, Downgrades, and Cancellations
                            If you created a Free Account but want to upgrade to a Paid Account, your upgrade will occur immediately upon payment of the relevant Subscription Fees and your Subscription Period will run from the date of your upgrade.

                            If you created or upgraded to a Paid Account, and you want to:

                            Upgrade to a different Subscription Plan: Your upgrade will occur immediately at a prorated rate upon payment of the price difference between the two Subscription Plans for the remainder of your Subscription Period. Your upgraded Subscription Plan will run until the end of the initial Subscription Period and will auto-renew as the upgraded Subscription Plan.
                            Cancel your Subscription Plan and/or downgrade your Subscription: Your downgrade will take place following the end of your current Subscription Period.
                            PLEASE NOTE THAT WHEN YOU DOWNGRADE YOUR ACCOUNT, YOU WILL ONLY BE ABLE TO ACCESS THE SERVICES AVAILABLE WITHIN YOUR NEW SUBSCRIPTION PLAN, AND THEREFORE YOU MAY LOSE ACCESS TO ANY ADDITIONAL FORMS OR ANY PREMIUM CONSENT PLATFORM FEATURES CREATED OR AVAILABLE THROUGH YOUR PREVIOUS SUBSCRIPTION PLAN.

                            How to Cancel a Subscription Plan
                            You can cancel your Subscription Plan at any time by logging into your account or contacting us using the contact information provided below. Your cancellation will take effect at the end of your current Subscription Period.

                            Except as stated in this Section, we will not be required to refund Subscription Fees under any circumstances.

                            If you are unsatisfied with our services, please email us at info@termly.io or call us at (855) 234-5020.

                            6. PROHIBITED ACTIVITIES
                            You may not access or use the Services for any purpose other than that for which we make the Services available. The Services may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us.

                            As a user of the Services, you agree not to:

                            Systematically retrieve data, Forms, or other Content from the Services to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.
                            Make any unauthorized use of the Services, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses.
                            Use a buying agent or purchasing agent to make purchases on the Services.
                            Use the Services to advertise or offer to sell goods and services.
                            Circumvent, disable, or otherwise interfere with security-related features of the Services, including features that prevent or restrict the use or copying of any Content or enforce limitations on the use of the Services and/or the Content contained therein.
                            Engage in unauthorized framing of or linking to the Services.
                            Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords.
                            Make improper use of our support services or submit false reports of abuse or misconduct.
                            Engage in any automated use of the Website or Services, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools.
                            Interfere with, disrupt, or create an undue burden on the Services or the networks or services connected to the Services.
                            Attempt to impersonate another user or person or use the username of another user.
                            Sell or otherwise transfer your Termly profile or account.
                            Use any information obtained from the Services in order to harass, abuse, or harm another person.
                            Use the Services as part of any effort to compete with us or otherwise use the Services and/or the Content for any revenue-generating endeavor or commercial enterprise beyond the license granted to you under these Terms of Use.
                            Decipher, decompile, disassemble, or reverse engineer any of the Software comprising or in any way making up a part of the Services.
                            Attempt to bypass any measures of the Website or Software designed to prevent or restrict access to the Services, or any portion of the Services.
                            Harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Services to you.
                            Delete the copyright or other proprietary rights notice from any Content.
                            Copy or adapt the Software, including but not limited to Flash, PHP, HTML, JavaScript, or other code.
                            Upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of capital letters and spamming (continuous posting of repetitive text), that interferes with any party’s uninterrupted use and enjoyment of the Software or the Services or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Software or the Services.
                            Upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including without limitation, clear graphics interchange formats (“gifs”), 1×1 pixels, web bugs, cookies, or other similar devices (sometimes referred to as “spyware” or “passive collection mechanisms” or “pcms”).
                            Except as may be the result of standard search engine or Internet browser usage, use, launch, develop, or distribute any automated system, including without limitation, any spider, robot, cheat utility, scraper, or offline reader that accesses the Software or the Services, or using or launching any unauthorized script or other software.
                            Disparage, tarnish, or otherwise harm, in our opinion, Termly, the Software, Website, and/or the Services.
                            Use the Services in a manner inconsistent with any applicable laws or regulations.
                            7. THIRD-PARTY WEBSITES AND CONTENT
                            The Services may contain (or you may be sent via the Services) links to other websites (“Third-Party Websites”) as well as articles, photographs, text, graphics, pictures, designs, music, sound, video, information, applications, software, and other content or items belonging to or originating from third parties (“Third-Party Content”). Such Third-Party Websites and Third-Party Content are not investigated, monitored, or checked for accuracy, appropriateness, or completeness by us, and we are not responsible for any Third-Party Websites accessed through the Services or any Third-Party Content posted on, available through, or installed from the Services, including the content, accuracy, offensiveness, opinions, reliability, privacy practices, or other policies of or contained in the Third-Party Websites or the Third-Party Content. Inclusion of, linking to, or permitting the use or installation of any Third-Party Websites or any Third-Party Content does not imply approval or endorsement thereof by us. If you decide to leave the Services and access the Third-Party Websites or to use or install any Third-Party Content, you do so at your own risk, and you should be aware these Terms of Use no longer govern.

                            You should review the applicable terms and policies, including privacy and data gathering practices, of any website to which you navigate from the Services or relating to any applications you use or install from the Services. Any purchases you make through Third-Party Websites will be through other websites and from other companies, and we take no responsibility whatsoever in relation to such purchases which are exclusively between you and the applicable third party. You agree and acknowledge that we do not endorse the products or services offered on Third-Party Websites and you shall hold us harmless from any harm caused by your purchase of such products or services. Additionally, you shall hold us harmless from any losses sustained by you or harm caused to you relating to or resulting in any way from any Third-Party Content or any contact with Third-Party Websites.

                            8. SERVICES MANAGEMENT
                            We reserve the right, but not the obligation, to: (1) monitor the Services for violations of these Terms of Use; (2) take appropriate legal action against anyone who, in our sole discretion, violates the law or these Terms of Use, including without limitation, reporting such user to law enforcement authorities; (3) in our sole discretion and without limitation, refuse, restrict access to, limit the availability of, or disable (to the extent technologically feasible) any of your contributions or any portion thereof; (4) in our sole discretion and without limitation, notice, or liability, to remove from the Services or otherwise disable all files and content that are excessive in size or are in any way burdensome to our systems; and (5) otherwise manage the Services in a manner designed to protect our rights and property and to facilitate the proper functioning of the Services.

                            9. PRIVACY NOTICE
                            We care about data privacy and security. Please review our Privacy Notice to understand our use of your personal information. You acknowledge that you have reviewed and understand our Privacy Notice.

                            Please be advised the Services is hosted in the United States. If you access the Services from any other region of the world with laws or other requirements governing personal data collection, use, or disclosure that differ from applicable laws in the United States, then through your continued use of the Services, you are transferring your data to the United States, and you agree to have your data transferred to and processed in the United States.

                            10. DIGITAL MILLENNIUM COPYRIGHT ACT (DMCA) NOTICE AND POLICY
                            Notifications
                            We respect the intellectual property rights of others. If you believe that any material available on or through the Services infringes upon any copyright you own or control, please immediately notify our Designated Copyright Agent using the contact information provided below (a “Notification”). A copy of your Notification will be sent to the person who posted or stored the material addressed in the Notification. Please be advised that pursuant to federal law you may be held liable for damages if you make material misrepresentations in a Notification. Thus, if you are not sure that material located on or linked to by the Services infringes your copyright, you should consider first contacting an attorney.

                            All Notifications should meet the requirements of DMCA 17 U.S.C. § 512(c)(3) and include the following information: (1) A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; (2) identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works on the Services are covered by the Notification, a representative list of such works on the Services; (3) identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material; (4) information reasonably sufficient to permit us to contact the complaining party, such as an address, telephone number, and, if available, an email address at which the complaining party may be contacted; (5) a statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and (6) a statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed upon.

                            Counter Notification
                            If you believe your own copyrighted material has been removed from the Services as a result of a mistake or misidentification, you may submit a written counter notification to our Designated Copyright Agent using the contact information provided below (a “Counter Notification”). To be an effective Counter Notification under the DMCA, your Counter Notification must include substantially the following: (1) identification of the material that has been removed or disabled and the location at which the material appeared before it was removed or disabled; (2) a statement that you consent to the jurisdiction of the Federal District Court in which your address is located, or if your address is outside the United States, for any judicial district in which we are located; (3) a statement that you will accept service of process from the party that filed the Notification or the party’s agent; (4) your name, address, and telephone number; (5) a statement under penalty of perjury that you have a good faith belief that the material in question was removed or disabled as a result of a mistake or misidentification of the material to be removed or disabled; and (6) your physical or electronic signature.

                            If you send us a valid, written Counter Notification meeting the requirements described above, we will restore your removed or disabled material, unless we first receive notice from the party filing the Notification informing us that such party has filed a court action to restrain you from engaging in infringing activity related to the material in question. Please note that if you materially misrepresent that the disabled or removed content was removed by mistake or misidentification, you may be liable for damages, including costs and attorney’s fees. Filing a false Counter Notification constitutes perjury.

                            Designated Copyright Agent
                            Termly Inc.
                            Attn: Copyright Agent
                            10929 Wickshire Way
                            North Bethesda, MD 20852
                            legal@termly.io

                            11. TERM AND TERMINATION
                            These Terms of Use shall remain in full force and effect while you use the Services. WITHOUT LIMITING ANY OTHER PROVISION OF THESE TERMS OF USE, WE RESERVE THE RIGHT TO, IN OUR SOLE DISCRETION AND WITHOUT NOTICE OR LIABILITY, DENY ACCESS TO AND USE OF THE SERVICES (INCLUDING BLOCKING CERTAIN IP ADDRESSES), TO ANY PERSON IF WE REASONABLY CONSIDER THAT SUCH PERSON IS IN BREACH OF THESE TERMS OF USE, OUR ACCEPTABLE USE POLICY, OR OF ANY APPLICABLE LAW OR REGULATION, INCLUDING WITHOUT LIMITATION BREACHES OF ANY REPRESENTATION, WARRANTY, OR COVENANT CONTAINED IN THESE TERMS OF USE.

                            WE MAY TERMINATE YOUR USE OR PARTICIPATION IN THE SERVICES OR DELETE YOUR ACCOUNT AND ANY CONTENT OR INFORMATION THAT YOU POSTED AT ANY TIME, WITHOUT WARNING, IN OUR SOLE DISCRETION IF WE CONSIDER THAT YOU HAVE BREACHED, OR ARE LIKELY TO BREACH, ANY OF THE ABOVE.

                            If we terminate or suspend your account for any reason, you are prohibited from registering and creating a new account under your name, a fake or borrowed name, or the name of any third party, even if you may be acting on behalf of the third party. In addition to terminating or suspending your account, we reserve the right to take appropriate legal action, including without limitation pursuing civil, criminal, and injunctive redress.

                            12. MODIFICATIONS AND INTERRUPTIONS
                            We reserve the right to change, modify, or remove the Content or the Services from time to time to comply with new laws or regulations or to update our offerings. We also reserve the right to modify or discontinue all or part of the Services if Termly were to close down or if we decide to change Termly’s business offering. We will not be liable to you or any third party for any modification, price change, suspension, or discontinuance of the Services.

                            We cannot guarantee the Services will be available at all times. We may experience hardware, software, or other problems or need to perform maintenance related to the Services, resulting in interruptions, delays, or errors. We reserve the right to change, revise, update, suspend, discontinue, or otherwise modify the Services from time to time and will endeavor to give you notice of such changes. You agree that we have no liability whatsoever for any loss, damage, or inconvenience caused by your inability to access or use the Services during any downtime or discontinuance of the Services.

                            Nothing in these Terms of Use will be construed to obligate us to maintain and support the Services or to supply any corrections, updates, or releases in connection therewith.

                            13. GOVERNING LAW
                            These Terms of Use and your use of the Services are governed by and construed in accordance with the laws of the State of Delaware applicable to agreements made and to be entirely performed within the State of Delaware, without regard to its conflict of law principles.

                            14. DISPUTE RESOLUTION
                            Informal Negotiations
                            To expedite resolution and control the cost of any dispute, controversy, or claim related to these Terms of Use (each a “Dispute” and collectively, the “Disputes”) brought by either you or us (individually, a “Party” and collectively, the “Parties”), the Parties agree to first attempt to negotiate any Dispute (except those Disputes expressly provided below) informally for at least thirty (30) days before initiating arbitration or litigation (as applicable per below). Such informal negotiations commence upon written notice from one Party to the other Party.

                            For our customers based in the United States, the following will apply:

                            Binding Arbitration
                            If the Parties are unable to resolve a Dispute through informal negotiations, the Dispute (except those Disputes expressly excluded below) will be finally and exclusively resolved by binding arbitration. YOU UNDERSTAND THAT WITHOUT THIS PROVISION, YOU WOULD HAVE THE RIGHT TO SUE IN COURT AND HAVE A JURY TRIAL. The arbitration shall be commenced and conducted under the Commercial Arbitration Rules of the American Arbitration Association (“AAA”) and, where appropriate, the AAA’s Supplementary Procedures for Consumer Related Disputes (“AAA Consumer Rules”), both of which are available at the AAA website. Your arbitration fees and your share of arbitrator compensation shall be governed by the AAA Consumer Rules and, where appropriate, limited by the AAA Consumer Rules. If such costs are determined by the arbitrator to be excessive, we will pay all arbitration fees and expenses. The arbitration may be conducted in person, through the submission of documents, by phone, or online. The arbitrator will make a decision in writing, but need not provide a statement of reasons unless requested by either Party. The arbitrator must follow applicable law, and any award may be challenged if the arbitrator fails to do so. Except where otherwise required by the applicable AAA rules or applicable law, the arbitration will take place in Kent County, DE. Except as otherwise provided herein, the Parties may litigate in court to compel arbitration, stay proceedings pending arbitration, or to confirm, modify, vacate, or enter judgment on the award entered by the arbitrator.

                            If for any reason, a Dispute proceeds in court rather than arbitration, the Dispute shall be commenced or prosecuted in the state and federal courts located in Kent County, DE, and the Parties hereby consent to, and waive all defenses of lack of personal jurisdiction, and forum non conveniens with respect to venue and jurisdiction in such state and federal courts. Application of the United Nations Convention on Contracts for the International Sale of Goods and the Uniform Computer Information Transaction Act (UCITA) are excluded from these Terms of Use.

                            In no event shall any Dispute brought by either Party related in any way to the Services be commenced more than one (1) year after the cause of action arose. If this provision is found to be illegal or unenforceable, then neither Party will elect to arbitrate any Dispute falling within that portion of this provision found to be illegal or unenforceable and such Dispute shall be decided by a court of competent jurisdiction within the courts listed for jurisdiction above, and the Parties agree to submit to the personal jurisdiction of that court.

                            Restrictions
                            The Parties agree that any arbitration shall be limited to the Dispute between the Parties individually. To the full extent permitted by law, (a) no arbitration shall be joined with any other proceeding; (b) there is no right or authority for any Dispute to be arbitrated on a class-action basis or to utilize class action procedures; and (c) there is no right or authority for any Dispute to be brought in a purported representative capacity on behalf of the general public or any other persons.

                            Exceptions to Informal Negotiations and Arbitration
                            The Parties agree that the following Disputes are not subject to the above provisions concerning informal negotiations and binding arbitration: (a) any Disputes seeking to enforce or protect, or concerning the validity of, any of the intellectual property rights of a Party; (b) any Dispute related to, or arising from, allegations of theft, piracy, invasion of privacy, or unauthorized use; and (c) any claim for injunctive relief. If this provision is found to be illegal or unenforceable, then neither Party will elect to arbitrate any Dispute falling within that portion of this provision found to be illegal or unenforceable and such Dispute shall be decided by a court of competent jurisdiction within the courts listed for jurisdiction above, and the Parties agree to submit to the personal jurisdiction of that court.

                            For our customers based outside of the United States:

                            If the Parties are unable to resolve a Dispute through informal negotiations as set out in this Section (see Informal Negotiations above), you hereby agree to the exclusive jurisdiction of the courts of Kent County, DE, in relation to any dispute which may arise in connection with these Terms of Use and/or your use and receipt of the Services.

                            15. CORRECTIONS
                            There may be information on the Services that contains typographical errors, inaccuracies, or omissions, including descriptions, pricing, availability, and various other information.

                            We reserve the right to correct any errors, inaccuracies, or omissions and to change or update the information on the Services at any time, without prior notice.

                            16. DISCLAIMER
                            THE SERVICES ARE PROVIDED ON AN “AS-IS” AND “AS-AVAILABLE” BASIS. YOU AGREE THAT YOUR USE OF OUR SERVICES WILL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE SOFTWARE OR THE SERVICES AND YOUR USE THEREOF, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.

                            WE MAKE NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE SERVICES, THE CONTENT OR ANY THIRD-PARTY CONTENT AND WE WILL ASSUME NO LIABILITY OR RESPONSIBILITY FOR ANY (1) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT AND MATERIALS, (2) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE SERVICES, (3) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (4) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICES, (5) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE SERVICES BY ANY THIRD PARTY, AND/OR (6) ANY ERRORS OR OMISSIONS IN ANY CONTENT AND MATERIALS OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SERVICES.

                            WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD-PARTY WEBSITE AND WE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND ANY THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.

                            17. LIMITATIONS OF LIABILITY
                            IN NO EVENT WILL WE OR TERMLY’S DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, OR ANY (DIRECT OR INDIRECT): (A) LOSS OF DATA, (B) LOST PROFIT, OR (C) LOST REVENUE OR OTHER DAMAGES ARISING FROM YOUR USE OF THE SERVICES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

                            NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE LESSER OF (A) THE AMOUNT PAID, IF ANY, BY YOU TO US DURING THE SIX (6) MONTH PERIOD PRIOR TO ANY CAUSE OF ACTION ARISING AND (B) THE SUM OF US$100.

                            CERTAIN STATE LAWS AND COUNTRIES’ LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.

                            18. INDEMNIFICATION
                            You agree to defend, indemnify, and hold us harmless, including our subsidiaries, affiliates, and all of our respective officers, agents, partners, and employees, from and against any loss, damage, liability, claim, or demand, including reasonable attorneys’ fees and expenses, made by any third party due to or arising out of: (1) your contributions; (2) use of the Services; (3) breach of these Terms of Use; (4) any breach of your representations and warranties set forth in these Terms of Use; (5) your violation of the rights of a third party, including but not limited to intellectual property rights; or (6) any overt harmful act toward any other user of the Services with whom you connected via the Services. Notwithstanding the foregoing, we reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate, at your expense, with our defense of such claims. We will use reasonable efforts to notify you of any such claim, action, or proceeding which is subject to this indemnification upon becoming aware of it.

                            19. USER DATA
                            We will maintain certain data that you transmit to the Services for the purpose of managing the performance of the Services, as well as data relating to your use of the Services. Although we perform regular routine backups of data, you are solely responsible for all data that you transmit or that relates to any activity you have undertaken using the Services.

                            You agree that we shall have no liability to you for any loss or corruption of any such data, and you hereby agree that you shall independently back up all your data and waive any right of action against us arising from any such loss or corruption of such data.

                            20. ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES
                            Visiting the Website or using the Services, sending us emails, and completing online forms constitute electronic communications. You consent to receive electronic communications, and you agree that all agreements, notices, disclosures, and other communications we provide to you electronically, via email and on the Services, satisfy any legal requirement that such communication be in writing.

                            YOU HEREBY AGREE TO THE USE OF ELECTRONIC SIGNATURES, CONTRACTS, ORDERS, AND OTHER RECORDS, AND TO ELECTRONIC DELIVERY OF NOTICES, POLICIES, AND RECORDS OF TRANSACTIONS INITIATED OR COMPLETED BY US OR VIA THE SERVICES.

                            You hereby waive any rights or requirements under any statutes, regulations, rules, ordinances, or other laws in any jurisdiction which require an original signature or delivery or retention of non-electronic records, or to payments or the granting of credits by any means other than electronic means.

                            21. CALIFORNIA USERS AND RESIDENTS
                            If any complaint with us is not satisfactorily resolved, you can contact the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs in writing at 1625 North Market Blvd., Suite N 112, Sacramento, California 95834 or by telephone at (800) 952-5210 or (916) 445-1254.

                            22. OTHER IMPORTANT INFORMATION
                            These Terms of Use and any policies or operating rules posted by us on the Services or in respect to the Services constitute the entire agreement and understanding between you and Termly. You confirm that you have not relied on any prior or side statement, agreement, or representation, whether these were oral or written, to enter into this agreement with us.

                            Our failure to exercise or enforce any right or provision of these Terms of Use shall not operate as a waiver of such right or provision. These Terms of Use operate to the fullest extent permissible by law.

                            We may assign any or all of our rights and obligations to others at any time.

                            If any provision or part of a provision of these Terms of Use is determined to be unlawful, void, or unenforceable, that provision or part of the provision is deemed severable from these Terms of Use and does not affect the validity and enforceability of any remaining provisions.

                            You and Termly are independent contractors and shall so represent ourselves in all regards. There is no joint venture, partnership, employment or agency relationship created between you and us as a result of these Terms of Use or use of the Services.

                            You hereby waive any and all defenses you may have based on the electronic form of these Terms of Use and the lack of signing by the parties hereto to execute these Terms of Use.

                            You and Termly agree that these Terms of Use will not be construed in favor of or against either party by reason of authorship.

                            You shall not (a) permit any third party to access or use the Services or Software in violation of any U.S. law or regulation; or (b) export any software provided by us or otherwise remove it from the United States except in compliance with all applicable U.S. laws and regulations. Without limiting the generality of the foregoing, you shall not permit any third party to access or use the Services in, or export the Software to, a country subject to a United States embargo (as of the Effective Date, Cuba, Iran, North Korea, Sudan, and Syria).

                            We may send notices pursuant to these Terms of Use to the email address you provided us, and such notices will be deemed received twenty-four (24) hours after they are sent. You may send notices pursuant to these Terms of Use to support@termly.io, and such notices will be deemed received seventy-two (72) hours after they are sent.

                            No delay, failure, or default, other than a failure to pay any fees when due, will constitute a breach of these Terms of Use to the extent such delay, failure, or default is caused by epidemics or pandemics, acts of war, terrorism, hurricanes, earthquakes, other acts of God or of nature, any law or any action taken by a government or public authority, non-performance by suppliers or subcontractors, interruption or failure of utility service, strikes or other labor disputes, riots or other acts of civil disorder, embargoes, or other causes beyond our reasonable control.

                            23. CONTACT US
                            In order to resolve a complaint regarding the Services or to receive further information regarding use of the Services, please contact us at:

                            Termly Inc.
                            8 The Grn Ste B
                            Dover, DE 19901
                            (855) 234-5020
                            info@termly.io
                        </div>                        
                    </div>
                </div>
            </div>
        </div>          
    </div>
</section>
@endsection